POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Well",
    "email": "well@well.com",
    "password": "23432535"
}

###
POST http://localhost:3003/create
Content-Type: application/json

{
    "title": "Pantanal",
    "description": "Após virar onça por causa de tanta raiva, Juma foge novamente, Juventino pousa no escuro da fazenda com o retrato do Velho do Rio.",
    "duration_in_minutes": "39min",
    "year_of_release": "2022/07/28"

}